# Generated by Django 6.0.1 on 2026-01-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contact',
            new_name='phone_number',
        ),
    ]
