# Generated by Django 6.0.1 on 2026-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_rank_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('none', 'None'), ('private', 'Private'), ('officer', 'Officer')], default='none', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('civilian', 'Civilian'), ('volunteer', 'Volunteer'), ('soldier', 'Soldier')], default='none', max_length=20, null=True),
        ),
    ]
