# Generated by Django 6.0.1 on 2026-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='short_bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
