# Generated by Django 6.0.1 on 2026-04-04 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('none', 'None'), ('private', 'Private'), ('officer', 'Officer')], default='none', max_length=30, null=True, verbose_name='Звання'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='short_bio',
            field=models.CharField(max_length=200, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('civilian', 'Civilian'), ('volunteer', 'Volunteer'), ('soldier', 'Soldier')], default='none', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
