# Generated by Django 6.0.1 on 2026-04-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_avatar_and_more'),
        ('users', '0013_alter_customuser_phone_number'),
    ]

    operations = [
    ]
