# Generated by Django 6.0.1 on 2026-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundraisingAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('current_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('operational_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
