# Generated by Django 6.0.1 on 2026-02-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraisingannouncement_author'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingannouncement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.unit'),
        ),
    ]
