# Generated by Django 6.0.1 on 2026-02-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='units_logo/')),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('agency', 'Структура'), ('branch', 'Рід військ'), ('corps', 'Корпус'), ('brigade', 'Бригада'), ('battalion', 'Батальйон'), ('special', 'Спецпідрозділ')], max_length=40)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='units.unit')),
            ],
        ),
    ]
