# Generated by Django 6.0.1 on 2026-03-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent',
            field=models.CharField(default='', max_length=255),
        ),
    ]
