# Generated by Django 6.0.1 on 2026-04-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundraisers', '0003_alter_fundraisingannouncement_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_document', models.FileField(upload_to='donation_document/')),
                ('photo', models.ImageField(upload_to='report_photo/')),
                ('description', models.TextField()),
                ('spent_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now=True)),
                ('fundraising_announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundraisers.fundraisingannouncement')),
            ],
        ),
    ]
