# Generated by Django 6.0.1 on 2026-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationdocument',
            name='description',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
