# Generated by Django 6.0.1 on 2026-02-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_remove_verificationdocument_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Деталі для верифікації/опис документів'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='requested_role',
            field=models.CharField(choices=[('military', 'Військовий'), ('volunteer', 'Волонтер'), ('foundation', 'Учасник благодійного фонду')], max_length=20, verbose_name='Хто ви?'),
        ),
    ]
